#ifndef __DOGMA_OPERAND_H_
#define __DOGMA_OPERAND_H_

enum dogma_operand {
  operandADD = 1,
  operandAGGM = 2,
  operandAGIM = 3,
  operandAGORSM = 4,
  operandAGRSM = 5,
  operandAIM = 6,
  operandALGM = 7,
  operandALM = 8,
  operandALRSM = 9,
  operandAND = 10,
  operandAORSM = 11,
  operandATT = 12,
  operandATTACK = 13,
  operandCARGOSCAN = 14,
  operandCHEATTELEDOCK = 15,
  operandCHEATTELEGATE = 16,
  operandCOMBINE = 17,
  operandDEC = 18,
  operandDECLOAKWAVE = 19,
  operandDECN = 20,
  operandDEFASSOCIATION = 21,
  operandDEFATTRIBUTE = 22,
  operandDEFBOOL = 23,
  operandDEFENVIDX = 24,
  operandDEFFLOAT = 25,
  operandDEFGROUP = 26,
  operandDEFINT = 27,
  operandDEFSTRING = 28,
  operandDEFTYPEID = 29,
  operandECMBURST = 30,
  operandEFF = 31,
  operandEMPWAVE = 32,
  operandEQ = 33,
  operandGA = 34,
  operandGET = 35,
  operandGETTYPE = 36,
  operandGM = 37,
  operandGT = 38,
  operandGTE = 39,
  operandIA = 40,
  operandIF = 41,
  operandINC = 42,
  operandINCN = 43,
  operandLAUNCH = 44,
  operandLAUNCHDEFENDERMISSILE = 45,
  operandLAUNCHDRONE = 46,
  operandLAUNCHFOFMISSILE = 47,
  operandLG = 48,
  operandLS = 49,
  operandMINE = 50,
  operandMUL = 51,
  operandOR = 52,
  operandPOWERBOOST = 53,
  operandRGGM = 54,
  operandRGIM = 55,
  operandRGORSM = 56,
  operandRGRSM = 57,
  operandRIM = 58,
  operandRLGM = 59,
  operandRLM = 60,
  operandRLRSM = 61,
  operandRORSM = 62,
  operandRS = 63,
  operandRSA = 64,
  operandSET = 65,
  operandSHIPSCAN = 66,
  operandSKILLCHECK = 67,
  operandSUB = 68,
  operandSURVEYSCAN = 69,
  operandTARGETHOSTILES = 70,
  operandTARGETSILENTLY = 71,
  operandTOOLTARGETSKILLS = 72,
  operandUE = 73,
  operandVERIFYTARGETGROUP = 74,
};

extern const char *operand_id_strings[];


#endif // __DOGMA_OPERAND_H_
